name: Solar system workflow
on: 
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "feature/*"

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}

jobs:
  unit-testing:
    name: Unit testing
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [20,21,22]
        exclude:
          - node-version: 20
            os: macos-latest
    runs-on: ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v5

      - name: setup nodejs version
        uses: actions/setup-node@v6
        with:
          node-version: ${{matrix.node-version}}

      - name: Install dependencies
        run: npm install

      - name: Run testing
        run: npm test

      - name: archive test result
        uses: actions/upload-artifact@v7
        with:
          name: mocha-artifact
          path: test-results.xml

