name: Solar system workflow
on: 
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "feature/*"

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}

jobs:
  unit-testing:
    name: Unit testing
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22]
        # exclude:
        #   - node-version: 21
        #     os: macos-latest
    runs-on: ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v5

      - name: setup nodejs version
        uses: actions/setup-node@v6
        with:
          node-version: ${{matrix.node-version}}

      - name: cache npm dependencies
        uses: actions/cache@v5
        with: 
          path: node_modules
          key: ${{ runner.os}}-node-modules-${{ hashFiles('package-lock.json')}}

      - name: Install dependencies
        run: npm install

      - name: Run testing
        id: unit-test
        run: npm test

      - name: archive test result
        uses: actions/upload-artifact@v7
        #if previous step fail or succes and this will always runs
        if: always()
        with:
          name: mocha-artifact
          path: test-results.xml

  code-coverage:

    runs-on: ubuntu-latest
    needs: unit-testing
    steps:
      - uses: actions/checkout@v5

      - name: setup nodejs version
        uses: actions/setup-node@v6
        with:
          node-version: ${{matrix.node-version}}

      - name: cache npm dependencies
        uses: actions/cache@v5
        with: 
          path: node_modules
          key: ${{ runner.os}}-node-modules-${{ hashFiles('package-lock.json')}}


      - name: Install dependencies
        run: npm install

      - name: code coverage
        continue-on-error: true
        run: npm run coverage
        
      - name: archive coverage results
        uses: actions/upload-artifact@v7
        with:
          name: Code-Coverage-Result
          path: coverage
          retention-days: 5


  docker-login:
    permissions:
      packages: write

    runs-on: ubuntu-latest
    needs: [unit-testing, code-coverage]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{ github.sha}}
            ghcr.io/${{github.repository_owner}}/github-actions-solar:${{github.sha}}